In [2]:
import numpy as np
import tensorflow as tf

In [3]:
a = np.array([
    [2.1,3.1,3.9],
    [3.2,4.5,3.1]
])

In [4]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [5]:
np.mean(a,axis=0)

array([2.65, 3.8 , 3.5 ])

In [6]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

### tensor라는 객체를 생성 <br>dtype은 float32로 정해지고 default는 int32 <br>name도 지정해줄 수 있다. 같은 이름을 같는 tensor를 생성할 수 없다.

In [16]:
with tf.name_scope('abc'):
    a = tf.constant(3,dtype=tf.float32,name='const')
print(a)

Tensor("abc_1/const:0", shape=(), dtype=float32)
