In [21]:
import numpy as np
import tensorflow as tf
import warnings
warnings.filterwarnings(action='ignore')

In [22]:
a = np.array([
    [2.1,3.1,3.9],
    [3.2,4.5,3.1]
])

In [23]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [24]:
np.mean(a,axis=0)

array([2.65, 3.8 , 3.5 ])

In [25]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

#### tensor라는 객체를 생성 <br>dtype은 float32로 정해지고 default는 int32 <br>name도 지정해줄 수 있다. 같은 이름을 같는 tensor를 생성할 수 없다.

In [41]:
with tf.name_scope('abc'):
    a = tf.constant(3,dtype=tf.float32,name='const')
    b = tf.Variable(0,dtype=tf.float32)
    c = tf.assign(b,a+b)
print(a)
print(b)
init = tf.global_variables_initializer()

Tensor("abc_9/const:0", shape=(), dtype=float32)
<tf.Variable 'abc_9/Variable:0' shape=() dtype=float32_ref>


#### 위에서는 아무것도 하지 않았다.####

In [46]:
with tf.Session() as sess:
    sess.run(init)
    print(a+b) # 아무것도 아닌 Tensor가 출력
    #print(sess.run(a+b)) # 이런식으로 사용하면 안좋다. a+b자체가 그래프를 그리는 것.
    print(sess.run(c))

Tensor("add_13:0", shape=(), dtype=float32)
3.0


constant : 값을 변경할 수 없다.<br>
constant에는 assign이 존재하지 않음<br>
값을 보존하고 변경하고 싶다면 Variable로 선언해야한다.

In [47]:
c = tf.assign(a,a+a)

AttributeError: 'Tensor' object has no attribute 'assign'

seed값은 고정해놓고 한다. (실험할 때마다 같은 seed로 반복하고 싶어서)
- 같은 seed로 하면 같은 결과가 나온다
- 컴퓨터가 생성하는 random number는 micro second로 잘라서 생성하는데<br>seed를 임의로 넣어주면 난수가 고정되는 것이다.

In [58]:
np.random.seed(42)
x = tf.placeholder(tf.float32, shape=(),name='x')
y = tf.placeholder(tf.float32, shape=(), name='y')
w = tf.Variable(np.random.randn(), dtype=tf.float32)
a = tf.assign(w,w+x+y)
init = tf.global_variables_initializer()

In [54]:
with tf.Session() as sess:
    sess.run(init)
    for _ in range(0,10):
        print(sess.run(w))
        sess.run(a) # placeholder에 아무것도 넣어 주지 않아 오류가 뜬다.
    print(sess.run(w))

1.6260831


InvalidArgumentError: You must feed a value for placeholder tensor 'x_2' with dtype float
	 [[node x_2 (defined at <ipython-input-53-f5bce06031ad>:1) ]]

Caused by op 'x_2', defined at:
  File "/home/pirl/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pirl/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/base_events.py", line 1764, in _run_once
    handle._run()
  File "/home/pirl/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-f5bce06031ad>", line 1, in <module>
    x = tf.placeholder(tf.float32, shape=(),name='x')
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5791, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/pirl/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'x_2' with dtype float
	 [[node x_2 (defined at <ipython-input-53-f5bce06031ad>:1) ]]


In [59]:
with tf.Session() as sess:
    sess.run(init)
    for _ in range(0,10):
        print(sess.run(w))
        sess.run(a, feed_dict={x:1.0, y:2.0}) # placeholder에 아무것도 넣어 주지 않아 오류가 뜬다.
    print(sess.run(w))

0.2329824
3.2329824
6.2329826
9.232983
12.232983
15.232983
18.232983
21.232983
24.232983
27.232983
30.232983
