In [21]:
import numpy as np
import tensorflow as tf
import warnings
warnings.filterwarnings(action='ignore')

In [22]:
a = np.array([
    [2.1,3.1,3.9],
    [3.2,4.5,3.1]
])

In [23]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [24]:
np.mean(a,axis=0)

array([2.65, 3.8 , 3.5 ])

In [25]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

#### tensor라는 객체를 생성 <br>dtype은 float32로 정해지고 default는 int32 <br>name도 지정해줄 수 있다. 같은 이름을 같는 tensor를 생성할 수 없다.

In [41]:
with tf.name_scope('abc'):
    a = tf.constant(3,dtype=tf.float32,name='const')
    b = tf.Variable(0,dtype=tf.float32)
    c = tf.assign(b,a+b)
print(a)
print(b)
init = tf.global_variables_initializer()

Tensor("abc_9/const:0", shape=(), dtype=float32)
<tf.Variable 'abc_9/Variable:0' shape=() dtype=float32_ref>


#### 위에서는 아무것도 하지 않았다.####

In [46]:
with tf.Session() as sess:
    sess.run(init)
    print(a+b) # 아무것도 아닌 Tensor가 출력
    #print(sess.run(a+b)) # 이런식으로 사용하면 안좋다. a+b자체가 그래프를 그리는 것.
    print(sess.run(c))

Tensor("add_13:0", shape=(), dtype=float32)
3.0


constant : 값을 변경할 수 없다.<br>
constant에는 a
값을 보존하고 변경하고 싶다면 Variable로 선언해야한다.

In [47]:
c = tf.assign(a,a+a)

AttributeError: 'Tensor' object has no attribute 'assign'